version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  ngrok:
    image: ngrok/ngrok:latest
    command: http backend:5000
    depends_on:
      - backend
    environment:
      - NGROK_AUTHTOKEN=2vtCyfUUssW0ilFICH0kl02z3KD_3WUKe6pDMpywGZZ1pN4Ev

volumes:
  db_data:
